### ISSUE TITLE
get_input fails

### ISSUE THREAD

**Issue by Skelmis** [Skelmis/DPY-Bot-Base#13]
```

AttributeError: 'Member' object has no attribute 'author',
    raise TimeoutError,
TimeoutError,
During handling of the above exception, another exception occurred:,
Traceback (most recent call last):,
  File "/usr/local/lib/python3.9/site-packages/nextcord/client.py", line 414, in _run_event,
  File "/usr/local/lib/python3.9/site-packages/bot_base/bot.py", line 179, in on_command_error,
    raise error,
    await coro(*args, **kwargs),
  File "/usr/local/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped,
    ret = await coro(*args, **kwargs),
  File "/pyro/cogs/review.py", line 76, in review_guild,
    return await ctx.author.send_basic_embed("Cancelling the process."),
    text=self.author.display_name, icon_url=self.author.avatar.url,
  File "/usr/local/lib/python3.9/site-packages/bot_base/wraps/meta.py", line 127, in send_basic_embed,
  File "/usr/local/lib/python3.9/site-packages/bot_base/wraps/member.py", line 29, in __getattr__,
    return getattr(self.person, item),
  File "/pyro/cogs/review.py", line 27, in get_input,
    answers.append(await self.get_input(ctx.author, question)),
  File "/pyro/cogs/review.py", line 74, in review_guild,
Ignoring exception in on_command_error
```

**Comment by Skelmis** [comment]
I think this relates to #14 so closing
